<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ch.unibe.germanistik</groupId>
        <artifactId>namenatlas</artifactId>
        <version>${namenatlas.version}</version>
    </parent>

    <artifactId>namenatlas-import</artifactId>
    <name>Familiennamenatlas Schweiz - raw data preparation</name>
    <description>
        Preparation of raw data and import to PostgreSQL
    </description>
    <packaging>jar</packaging>

    <properties>
        <validate-etdb-import></validate-etdb-import>
        <validate-locations></validate-locations>
        <validate-types-tokens-hls></validate-types-tokens-hls>
        <validate-types-tokens-bfs></validate-types-tokens-bfs>
        <bfs-data.filename>${basedir}/../../NACHNAMEN_TOTAL_2020.csv</bfs-data.filename>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>namenatlas-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-util</artifactId>
        </dependency>
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>locations</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/database/locations.csv</missing>
                </file>
            </activation>
            <properties>
                <validate-locations>,locations</validate-locations>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-locations</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.Locations</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/database/locations.csv</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>generate-locations-for-place-of-origin</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.PlacesOfOrigin</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/intermediate/locations-for-place-of-origin.csv</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>etdb-import</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/database/etdb-import.csv</missing>
                </file>
            </activation>
            <properties>
                <validate-etdb-import>,etdb-import</validate-etdb-import>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-etdb-import</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.EtymologicalData</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/database/etdb-import.csv</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>types-tokens-hls</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/intermediate/types-tokens.hls.csv</missing>
                </file>
            </activation>
            <properties>
                <validate-types-tokens-hls>,types-tokens-hls</validate-types-tokens-hls>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-types-tokens-hls</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.TypesTokensHLS</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/intermediate/types-tokens.hls.csv</argument>
                                    </arguments>
                                    <systemProperties>
                                        <property>
                                            <key>bfs-data.filename</key>
                                            <value>${bfs-data.filename}</value>
                                        </property>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>locactions-bfs-origin</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/intermediate/locations-for-origin.bfs.csv</missing>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <?m2e execute onConfiguration,onIncremental?>
                                <id>generate-locations-for-origin</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <!-- slightly mis-use the "generate-test-resources" phase -->
                                <!-- in order to have the generated file available before -->
                                <!-- the "test" phase, because the tests for profile      -->
                                <!-- "types-tokens-bfs" depend on it                      -->
                                <phase>generate-test-resources</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.LocationsForBFSOrigin</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/intermediate/locations-for-origin.bfs.csv</argument>
                                    </arguments>
                                    <systemProperties>
                                        <property>
                                            <key>bfs-data.filename</key>
                                            <value>${bfs-data.filename}</value>
                                        </property>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>locactions-bfs-municipality</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/intermediate/locations-for-municipality.bfs.csv</missing>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <?m2e execute onConfiguration,onIncremental?>
                                <id>generate-locations-for-municipality</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <!-- slightly mis-use the "generate-test-resources" phase -->
                                <!-- in order to have the generated file available before -->
                                <!-- the "test" phase, because the tests for profile      -->
                                <!-- "types-tokens-bfs" depend on it                      -->
                                <phase>generate-test-resources</phase>
                                <configuration>
                                    <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.LocationsForBFSResidence</mainClass>
                                    <arguments>
                                        <argument>${basedir}/src/main/resources/intermediate/locations-for-municipality.bfs.csv</argument>
                                    </arguments>
                                    <systemProperties>
                                        <property>
                                            <key>bfs-data.filename</key>
                                            <value>${bfs-data.filename}</value>
                                        </property>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>types-tokens-bfs</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/intermediate/types-tokens.bfs.csv</missing>
                </file>
            </activation>
            <properties>
                <validate-types-tokens-bfs>,types-tokens-bfs</validate-types-tokens-bfs>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-types-tokens-bfs</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.TypesTokensBFS</mainClass>
                            <arguments>
                                <argument>${basedir}/src/main/resources/intermediate/types-tokens.bfs.csv</argument>
                            </arguments>
                            <systemProperties>
                                <property>
                                    <key>bfs-data.filename</key>
                                    <value>${bfs-data.filename}</value>
                                </property>
                            </systemProperties>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>types</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/database/types.csv</missing>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-types</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.Types</mainClass>
                            <arguments>
                                <argument>${basedir}/src/main/resources/database/types.csv</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>tokens</id>
            <activation>
                <file>
                    <missing>${basedir}/src/main/resources/database/tokens.csv</missing>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-tokens</id>
                                <goals>
                                    <goal>java</goal>
                                </goals>
                                <phase>prepare-package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>ch.unibe.germanistik.namenatlas.datapreparation.Tokens</mainClass>
                            <arguments>
                                <argument>${basedir}/src/main/resources/database/tokens.csv</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>raw-data/**</exclude>
                        <exclude>intermediate/**</exclude>
                        <exclude>database/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                    <groups>default${validate-locations}${validate-types-tokens-hls}${validate-types-tokens-bfs}${validate-etdb-import}</groups>
                    <systemPropertyVariables>
                        <bfs-data.filename>${bfs-data.filename}</bfs-data.filename>
                    </systemPropertyVariables>
                    <additionalClasspathElements>
                        <additionalClasspathElement>${basedir}/src/main/resources</additionalClasspathElement>
                    </additionalClasspathElements>
                    <disableXmlReport>true</disableXmlReport>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>src/main/resources/database/assembly.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
