package ch.unibe.germanistik.namenatlas.query;

import java.util.Map;

import io.swagger.v3.jaxrs2.ReaderListener;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.integration.api.OpenApiReader;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.ComposedSchema;
import io.swagger.v3.oas.models.media.Discriminator;

/**
 * {@link ReaderListener} to fix the generated OpenAPI definition for schemas using {@link Schema#oneOf()}
 * and {@link Schema#discriminatorProperty()}.
 *
 * The intended use case is a type hierarchy with a super class defined like this:
 * <pre>
 * {@code
 * @Schema(
 *   oneOf = {
 *      Subclass1.class, Subclass2.class
 *   },
 *   discriminatorProperty = "schema"
 *   )
 * }
 * public abstract class Superclass {
 *    // Discriminator property intended for inheritance in subclasses
 *    public String getSchema() { ... }
 * }
 * </pre>
 *
 * In this case, the default OpenAPI definition generated by Swagger-Core will contain both
 * the "oneOf" keyword and a "schema" property, which contradicts the OAS spec.
 *
 * To fix this, this {@code ReaderListener} removes any property whose name matches the
 * value of the discriminator property from a generated schema that defines both "oneOf"
 * and a discriminator property name.
 */
@OpenAPIDefinition
public final class FixOneOfOpenAPIDefinition implements ReaderListener {

    @Override
    public void beforeScan(OpenApiReader reader, OpenAPI openAPI) {}

    @Override
    public void afterScan(OpenApiReader reader, OpenAPI openAPI) {
        openAPI.getComponents()
               .getSchemas()
               .values()
               .stream()
               .filter(schema -> (schema instanceof ComposedSchema))
               .map(schema -> ComposedSchema.class.cast(schema))
               .filter(schema -> {
                   return schema.getDiscriminator() != null
                       && schema.getDiscriminator().getPropertyName() != null
                       && schema.getOneOf() != null
                       && schema.getProperties() != null;
                })
               .forEach(schema -> {
                    Discriminator discriminator = schema.getDiscriminator();
                    Map<String,?> properties = schema.getProperties();
                    assert discriminator != null && properties != null: "@AssumeAssertion(nullness) - see filter above";
                    properties.remove(discriminator.getPropertyName());
                    if (schema.getRequired() != null) {
                        schema.getRequired().remove(discriminator.getPropertyName());
                    }
               });
    }
}
