<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>namenatlas</artifactId>
        <groupId>ch.unibe.germanistik</groupId>
        <version>${namenatlas.version}</version>
    </parent>
    <name>Familiennamenatlas Schweiz - web application</name>
    <description>REST API and HTML/Typescript frontend</description>
    <artifactId>namenatlas-webapp</artifactId>
    <packaging>war</packaging>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>namenatlas-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-util</artifactId>
        </dependency>
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-servlet-2.x</artifactId>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-locator</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>swagger-ui</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
        </dependency>
    </dependencies>
    <build>
        <finalName>ROOT</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>src/main/typescript/client/</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <webResources>
                        <resource>
                          <directory>target/javascript</directory>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <configuration>
                    <alwaysResolveAppPath>false</alwaysResolveAppPath>
                    <outputFileName>openapi</outputFileName>
                    <openapiFilePath>${basedir}/src/main/openapi-stub.yaml</openapiFilePath>
                    <outputPath>${project.build.directory}/namenatlas/api/</outputPath>
                    <outputFormat>YAML</outputFormat>
                    <applicationClass>ch.unibe.germanistik.namenatlas.webapp.api.RestApi</applicationClass>
                    <prettyPrint>TRUE</prettyPrint>
                </configuration>
                <executions>
                    <execution>
                        <?m2e execute onConfiguration,onIncremental?>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!--
                Link to the documentation.
                https://openapi-generator.tech/docs/generators
                https://openapi-generator.tech/docs/generators/typescript-fetch
            -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>5.4.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <?m2e execute onConfiguration,onIncremental?>
                        <phase>compile</phase>
                        <configuration>
                            <inputSpec>${project.build.directory}/namenatlas/api/openapi.yaml</inputSpec>
                            <generatorName>typescript-fetch</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <output>${project.basedir}/src/main/typescript/client</output>
                            <typeMappings>GlobalFetch=WindowOrWorkerGlobalScope</typeMappings>
                            <configOptions>
                                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                                <typescriptThreePlus>true</typescriptThreePlus>
                                <enumPropertyNaming>UPPERCASE</enumPropertyNaming>
                            </configOptions>
                            <instantiationTypes>Array=array,Array=Set</instantiationTypes>
                            <typeMappings>Array=array,Array=Set</typeMappings>
                            <templateDirectory>${project.basedir}/src/main/mustache</templateDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <?m2e execute onConfiguration,onIncremental?>
                        <id>tsc</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <?m2e execute onConfiguration,onIncremental?>
                        <phase>compile</phase>
                        <configuration>
                            <workingDirectory>${project.basedir}/src/main/typescript</workingDirectory>
                            <executable>tsc</executable>
                        </configuration>
                    </execution>
                </executions>
            </plugin>



        </plugins>
    </build>
</project>
